adding project initilization workflow

diff --git a/.github/workflows/init-project.yml b/.github/workflows/init-project.yml
--- a/.github/workflows/init-project.yml
+++ b/.github/workflows/init-project.yml
@@ -1,14 +1,14 @@
 name: Deploy to Cloudzilla
 on:
   push:
-    branches: [main]
+    branches: [master]
   workflow_dispatch:
 
 env:
-  IMAGE_PREFIX: registry.cloudzilla.ai/rc-project-91/
+  IMAGE_PREFIX: registry.cloudzilla.ai/rc-project-7cb1a7a25b/
 
 jobs:
-  build-push:
+  cz-build-push:
     runs-on: ubuntu-latest
     permissions:
       contents: read
@@ -22,7 +22,7 @@ jobs:
         uses: docker/login-action@v3
         with:
           registry: https://registry.cloudzilla.ai/
-          username: 'robot$rc-project-91+imageuser'
+          username: 'robot$rc-project-7cb1a7a25b+imageuser'
           password: '${{ secrets.DOCKER_PASSWORD }}'
 
       - name: downcase REPO
@@ -36,11 +36,51 @@ jobs:
         with:
           images: ${{ env.IMAGE_PREFIX }}${{ env.IMAGE_NAME }}
 
+      - name: Valiate existing .env file
+        run: |
+          # Path to your .env file
+          ENV_FILE=".env"
+          # Check if the .env file exists
+          if [ ! -f "$ENV_FILE" ]; then
+              # If the .env file doesn't exist, exit the script
+              exit 0
+          fi
+
+          # Read the .env file line by line
+          while IFS= read -r line || [ -n "$line" ]; do
+              # Remove leading and trailing whitespace
+              line="$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
+
+              # Skip empty lines
+              if [ -z "$line" ]; then
+                  continue
+              fi
+
+              # Skip comment lines starting with #
+              if [[ "$line" == \#* ]]; then
+                  continue
+              fi
+
+              # Check if the line matches KEY=VALUE format
+              if ! [[ "$line" =~ ^[A-Za-z_][A-Za-z0-9_]*=.*$ ]]; then
+                  echo "Your existing .env file is not valid. Environment variable names (keys) must consist solely of letters, digits, and the underscore ( _ ) and must not begin with a digit according to the .env file specification"
+                  exit 1
+              fi
+          done < "$ENV_FILE"
+
+      - name: Put down .env file
+        run: |
+          echo "writing .env file..."
+          echo "# This file is generated or updated by the cloudzilla deploy workflow" >> .env
+          # remove duplicates keeping the items at the bottom of the file
+          tac .env | awk -F'=' '!seen[$1]++' | tac > .env.tmp2 && mv .env.tmp2 .env
+
       - name: Build and push Docker image
         uses: docker/build-push-action@v5
         with:
           context: .
           push: true
+          file: .github/workflows/cloudzilla/Dockerfile
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
 
@@ -49,91 +89,62 @@ jobs:
           SECTION_K8S_API_URL: '${{ secrets.SECTION_K8S_API_URL }}'
           SECTION_API_TOKEN: '${{ secrets.SECTION_API_TOKEN }}'
           DOCKER_SERVER: 'registry.cloudzilla.ai'
-          DOCKER_USERNAME: 'robot$rc-project-91+imageuser'
+          DOCKER_USERNAME: 'robot$rc-project-7cb1a7a25b+imageuser'
           DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
           FULL_IMAGE_WITH_TAG: '${{ env.DOCKER_METADATA_OUTPUT_TAGS }}'
           POD_NAME: '${{ env.IMAGE_NAME }}'
           DEBUG: 1
         run: |
           #!/bin/bash
-          # set -o xtrace
-          set -o errexit
-
+          test -z "${DEBUG}" || set -o xtrace
+          set +e  # revert the default `set -e` which github actions enable automatically
           cd "$(dirname "$0")"
 
           cert=/etc/ssl/certs/ca-certificates.crt
 
+          # Reusable backoffretry function
           backoffretry() {
-            set +o errexit
-          command="$@"
-          # Maximum number of retries
-          max_retries=4
-          # Initial delay between retries (in seconds)
-          initial_delay=5
-          # Multiplier for exponential backoff
-          multiplier=2
+              local max_retries=$1     # Maximum number of retries
+              local delay=$2           # Initial delay in seconds
+              shift 2
+              local command="$@"       # Command to execute (e.g., main function)
+              local attempt=1          # Current attempt counter
 
-          output=""
+              while [ $attempt -le $max_retries ]; do
+                  echo "Attempt $attempt of $max_retries"
 
-          # Capture the output and return code
-          attempt=0
-          while [ $attempt -lt $max_retries ]; do
-            output=$(eval "$command" 2>&1)
-            return_code=$?
+                  # Execute the command
+                  $command
+                  local exit_code=$?
 
-            if [ $return_code -eq 0 ]; then
-              # echo "The command was successful."
-              # echo "Output: $output"
-              echo "$output"
-              break
-            else
-              echo "The command failed with return code $return_code."
-              echo "Output: $output"
-              attempt=$((attempt + 1))
-              if [ $attempt -lt $max_retries ]; then
-                delay=$((initial_delay * multiplier ** (attempt - 1)))
-                echo "Retrying in $delay seconds..."
-                sleep $delay
-              fi
-            fi
-          done
+                  if [ $exit_code -eq 0 ]; then
+                      echo "Success on attempt $attempt"
+                      return 0
+                  else
+                      echo "Failure on attempt $attempt with exit code $exit_code"
+                  fi
 
-          if [ $return_code -ne 0 ]; then
-            echo "The command failed after $max_retries attempts."
-          fi
-          set -o errexit
+                  if [ $attempt -lt $max_retries ]; then
+                      echo "Waiting for $delay seconds before retry..."
+                      sleep $delay
+                      delay=$((delay * 2)) # Exponential backoff
+                      attempt=$((attempt + 1))
+                  else
+                      echo "Exceeded maximum retries. Exiting with failure."
+                      return $exit_code
+                  fi
+              done
           }
 
           main() {
-            setCluster
-            createOutput=$(backoffretry "kubectl create secret docker-registry regcred --docker-server=\"${DOCKER_SERVER}\" --docker-username=\"${DOCKER_USERNAME}\" --docker-password=\"${DOCKER_PASSWORD}\" --dry-run=client -o yaml | kubectl apply -f - ")
-            echo "$createOutput"
+            setCluster || return 1
 
-            # Check if the output contains the string 'created'
-            if echo "$createOutput" | grep -q 'created'; then
-              echo "The output contains the string 'created', might indicate a problem as we expect updated, retrying."
-              sleep 10 # sleep while the error is resolving on the servers
-              backoffretry "kubectl create secret docker-registry regcred --docker-server=\"${DOCKER_SERVER}\" --docker-username=\"${DOCKER_USERNAME}\" --docker-password=\"${DOCKER_PASSWORD}\" --dry-run=client -o yaml | kubectl apply -f - "
-            fi
-
-            deploymentOutput=$(envsubst '$FULL_IMAGE_WITH_TAG $POD_NAME' < ${GITHUB_WORKSPACE}/k8s/deploy.yaml | kubectl apply -f - )
-            echo "$deploymentOutput"
-            # Check if the output contains the string 'created'
-            if echo "$deploymentOutput" | grep -q 'created'; then
-              echo "The deployment output contains the string 'created', might indicate a problem as we expect updated, retrying."
-              sleep 10 # sleep while the error is resolving on the servers
-              backoffretry "kubectl create secret docker-registry regcred --docker-server=\"${DOCKER_SERVER}\" --docker-username=\"${DOCKER_USERNAME}\" --docker-password=\"${DOCKER_PASSWORD}\" --dry-run=client -o yaml | kubectl apply -f - "
-            fi
-
-            ingressOutput=$(backoffretry "kubectl apply -f ${GITHUB_WORKSPACE}/k8s/ingress-upstream.yaml")
-            echo "$ingressOutput"
-            # Check if the output contains the string 'created'
-            if echo "$ingressOutput" | grep -q 'created'; then
-              echo "The deployment output contains the string 'created', might indicate a problem as we expect updated, retrying."
-              sleep 10 # sleep while the error is resolving on the servers
-              backoffretry "kubectl create secret docker-registry regcred --docker-server=\"${DOCKER_SERVER}\" --docker-username=\"${DOCKER_USERNAME}\" --docker-password=\"${DOCKER_PASSWORD}\" --dry-run=client -o yaml | kubectl apply -f - "
-            fi
-            backoffretry "kubectl rollout restart deployment \"section-project-deployment\""
+            kubectl create secret generic console-project-env-secret --from-env-file=${GITHUB_WORKSPACE}/.env --dry-run=client -o yaml | kubectl apply -f - || return 1
+            kubectl create secret docker-registry regcred --docker-server="${DOCKER_SERVER}" --docker-username="${DOCKER_USERNAME}" --docker-password="${DOCKER_PASSWORD}" --dry-run=client -o yaml | kubectl apply -f - || return 1
+            kubectl apply -f ${GITHUB_WORKSPACE}/.github/workflows/cloudzilla/k8s/ingress-upstream.yaml || return 1
+            envsubst '$FULL_IMAGE_WITH_TAG $POD_NAME' < ${GITHUB_WORKSPACE}/.github/workflows/cloudzilla/k8s/deploy.yaml | kubectl apply -f - || return 1
+            kubectl rollout restart deployment "section-project-deployment" || return 1
+           
           }
 
           setCluster() {
@@ -146,15 +157,22 @@ jobs:
 
             kubectl config set-cluster section \
             --server=$SECTION_K8S_API_URL \
-            --certificate-authority=$cert
+            --certificate-authority=$cert || return 1
 
-            kubectl config set-credentials section-user --token=$SECTION_API_TOKEN
+            kubectl config set-credentials section-user --token=$SECTION_API_TOKEN || return 1
 
-            kubectl config set-context my-section-application --cluster=section --user=section-user --namespace=default
+            kubectl config set-context my-section-application --cluster=section --user=section-user --namespace=default || return 1
 
-            kubectl config use-context my-section-application
+            kubectl config use-context my-section-application || return 1
 
-            kubectl version
+            kubectl version || return 1
           }
-          main
-          "$@"
+
+          # Parameters for backoffretry
+          max_retries=4        # Maximum number of retries
+          initial_delay=10     # Initial delay before retrying in seconds
+
+          # Call backoffretry with the main function
+          backoffretry $max_retries $initial_delay main
+          exit_code=$?
+          exit $exit_code
